class CfgPatches
{
	class euroseals_weapons_config
	{
		units[]=
		{

		};
		weapons[]=
		{
			"eus_hlc_rifle_bcmjack",
		};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"A3_Data_F",
			"A3_UI_F",
			"A3_Anims_F",
			"A3_Anims_F_Config_Sdr",
			"A3_Weapons_F",
			"asdg_jointrails",
			"hlcweapons_core",
			"hlcweapons_ar15",
		};
	};
};

class cfgWeapons
{
	class eus_hlc_rifle_bcmjack: hlc_rifle_bcmjack
	{
		author="Twinke Masta, Tenoyl, Tigg, Toadie, Mitsu";
		reloadAction="HLC_GestureReloadAR15_catch_WS";
		scope=2;
		magazines[]=
		{
			"30Rnd_556x45_Stanag",
			"hlc_30rnd_556x45_EPR",
			"hlc_30rnd_556x45_SOST",
			"hlc_30rnd_556x45_SPR",
			"hlc_50rnd_556x45_EPR",
			"30Rnd_556x45_Stanag_Tracer_Red",
			"30Rnd_556x45_Stanag_Tracer_Green",
			"30Rnd_556x45_Stanag_Tracer_Yellow"
		};
		model="hlc_wp_ar15\mesh\JackCarbine\samr.p3d";
		picture="\hlc_wp_ar15\tex\ui\gear_jack_x_ca";
		UiPicture="\A3\weapons_f\data\UI\icon_regular_CA.paa";
		displayName="BCM 'Jack' Carbine";
		descriptionShort="Assault rifle<br/>Caliber: 5.56mm";
		discretedistance[]={100,150,200,250,300,350,400};
		discretedistanceinitindex=0;
		bg_bipod=0;
		reloadMagazineSound[]=
		{
			"hlc_wp_ar15\snd\ar15_reload_A3_std",
			0.74000001,
			1,
			30
		};
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"hlc_wp_ar15\gesture\newgesture\carbine_hands.rtm"
		};
		opticszoominit=0.75;
		opticszoommax=1.1;
		opticszoommin=0.375;
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=24;
			class MuzzleSlot: SlotInfo
			{
				linkProxy="\A3\data_f\proxies\weapon_slots\MUZZLE";
				compatibleItems[]=
				{
					"hlc_muzzle_556NATO_KAC"
				};
			};
			class CowsSlot: CowsSlot
			{
				compatibleItems[]={};
			};
			class PointerSlot: PointerSlot
			{
				compatibleItems[]={};
			};
			class asdg_OpticRail_Jack: asdg_OpticRail1913
			{
			};
			class asdg_FrontSideRail_Jack: asdg_FrontSideRail
			{
			};
		};
		class ItemInfo
		{
			priority=1;
			RMBhint="XMC";
			onHoverText="TODO XMC DSS";
		};
		class Single: Mode_SemiAuto
		{
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				weaponSoundEffect="DefaultRifle";
				closure1[]=
				{
					"\hlc_wp_ar15\snd\jack_carbine_first",
					1,
					1,
					10
				};
				closure2[]=
				{
					"\hlc_wp_ar15\snd\jack_carbine_first",
					1,
					1,
					10
				};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\hlc_wp_ar15\snd\jack_carbine_fire",
					1,
					1,
					1200
				};
				begin2[]=
				{
					"\hlc_wp_ar15\snd\jack_carbine_fire",
					1,
					1,
					1200
				};
				begin3[]=
				{
					"\hlc_wp_ar15\snd\jack_carbine_fire",
					1,
					1,
					1200
				};
				soundBegin[]=
				{
					"begin1",
					0.33000001,
					"begin2",
					0.33000001,
					"begin3",
					0.34
				};
			};
			class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\hlc_wp_ar15\snd\diplomat_suppressed",
					1,
					1,
					200
				};
				begin2[]=
				{
					"\hlc_wp_ar15\snd\diplomat_suppressed",
					1,
					1,
					200
				};
				soundBegin[]=
				{
					"begin1",
					0.5,
					"begin2",
					0.5
				};
			};
			begin1[]=
			{
				"hlc_wp_ar15\snd\jack_carbine_fire",
				1,
				1,
				1200
			};
			begin2[]=
			{
				"hlc_wp_ar15\snd\jack_carbine_fire",
				1,
				1,
				1200
			};
			soundBegin[]=
			{
				"begin1",
				0.5,
				"begin2",
				0.5
			};
			closure1[]=
			{
				"hlc_wp_ar15\snd\jack_carbine_first",
				1,
				1,
				30
			};
			closure2[]=
			{
				"hlc_wp_ar15\snd\jack_carbine_first",
				1,
				1,
				30
			};
			soundClosure[]=
			{
				"closure1",
				0.5,
				"closure2",
				0.5
			};
			weaponSoundEffect="DefaultRifle";
			reloadTime=0.071000002;
			recoil="recoil_single_mk20";
			recoilProne="recoil_single_prone_mk20";
			dispersion=0.00013090001;
			minRange=2;
			minRangeProbab=0.7;
			midRange=225;
			midRangeProbab=0.69999999;
			maxRange=400;
			maxRangeProbab=0.3;
		};
		class FullAuto: Mode_FullAuto
		{
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				weaponSoundEffect="DefaultRifle";
				closure1[]=
				{
					"\hlc_wp_ar15\snd\jack_carbine_first",
					1,
					1,
					10
				};
				closure2[]=
				{
					"\hlc_wp_ar15\snd\jack_carbine_first",
					1,
					1,
					10
				};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\hlc_wp_ar15\snd\jack_carbine_fire",
					1,
					1,
					1200
				};
				begin2[]=
				{
					"\hlc_wp_ar15\snd\jack_carbine_fire",
					1,
					1,
					1200
				};
				begin3[]=
				{
					"\hlc_wp_ar15\snd\jack_carbine_fire",
					1,
					1,
					1200
				};
				soundBegin[]=
				{
					"begin1",
					0.33000001,
					"begin2",
					0.33000001,
					"begin3",
					0.34
				};
			};
			class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\hlc_wp_ar15\snd\diplomat_suppressed",
					1,
					1,
					200
				};
				begin2[]=
				{
					"\hlc_wp_ar15\snd\diplomat_suppressed",
					1,
					1,
					200
				};
				soundBegin[]=
				{
					"begin1",
					0.5,
					"begin2",
					0.5
				};
			};
			begin1[]=
			{
				"hlc_wp_ar15\snd\jack_carbine_fire",
				1,
				1,
				1200
			};
			begin2[]=
			{
				"hlc_wp_ar15\snd\jack_carbine_fire",
				1,
				1,
				1200
			};
			soundBegin[]=
			{
				"begin1",
				0.5,
				"begin2",
				0.5
			};
			closure1[]=
			{
				"hlc_wp_ar15\snd\jack_carbine_first",
				1,
				1,
				30
			};
			closure2[]=
			{
				"hlc_wp_ar15\snd\jack_carbine_first",
				1,
				1,
				30
			};
			soundClosure[]=
			{
				"closure1",
				0.5,
				"closure2",
				0.5
			};
			weaponSoundEffect="DefaultRifle";
			reloadTime=0.071000002;
			recoil="recoil_auto_mk20";
			recoilProne="recoil_auto_prone_mk20";
			dispersion=0.00013090001;
			maxrange=100;
			maxrangeprobab=0.050000001;
			midrange=30;
			midrangeprobab=0.69999999;
			minrange=1;
			minrangeprobab=0.30000001;
			aiRateOfFire=1e-006;
		};
		class Library
		{
			libTextDesc="BCM5 - Jack II";
		};
	};
};